# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Chang/Documents/ECE4534/Raspi/form/mainwidget.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName("MainWidget")
        MainWidget.resize(800, 480)
        MainWidget.setWindowTitle("")
        self.mainTabWidget = QtWidgets.QTabWidget(MainWidget)
        self.mainTabWidget.setGeometry(QtCore.QRect(0, 10, 800, 470))
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.configTab = QtWidgets.QWidget()
        self.configTab.setObjectName("configTab")
        self.simulationButton = QtWidgets.QPushButton(self.configTab)
        self.simulationButton.setGeometry(QtCore.QRect(50, 30, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.simulationButton.setFont(font)
        self.simulationButton.setObjectName("simulationButton")
        self.mainTabWidget.addTab(self.configTab, "")
        self.mappingTab = QtWidgets.QWidget()
        self.mappingTab.setObjectName("mappingTab")
        self.mappingGraphicsView = QtWidgets.QGraphicsView(self.mappingTab)
        self.mappingGraphicsView.setGeometry(QtCore.QRect(12, 0, 770, 430))
        self.mappingGraphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mappingGraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mappingGraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mappingGraphicsView.setObjectName("mappingGraphicsView")
        self.mainTabWidget.addTab(self.mappingTab, "")
        self.debugTab = QtWidgets.QWidget()
        self.debugTab.setObjectName("debugTab")
        self.debugTextEdit = QtWidgets.QTextEdit(self.debugTab)
        self.debugTextEdit.setGeometry(QtCore.QRect(12, 0, 770, 430))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        self.debugTextEdit.setFont(font)
        self.debugTextEdit.setObjectName("debugTextEdit")
        self.mainTabWidget.addTab(self.debugTab, "")
        self.manualTab = QtWidgets.QWidget()
        self.manualTab.setObjectName("manualTab")
        self.directionGroupBox = QtWidgets.QGroupBox(self.manualTab)
        self.directionGroupBox.setGeometry(QtCore.QRect(260, 100, 300, 240))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.directionGroupBox.setFont(font)
        self.directionGroupBox.setObjectName("directionGroupBox")
        self.upButton = QtWidgets.QPushButton(self.directionGroupBox)
        self.upButton.setGeometry(QtCore.QRect(110, 50, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.upButton.setFont(font)
        self.upButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.upButton.setObjectName("upButton")
        self.downButton = QtWidgets.QPushButton(self.directionGroupBox)
        self.downButton.setGeometry(QtCore.QRect(110, 140, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.downButton.setFont(font)
        self.downButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.downButton.setObjectName("downButton")
        self.leftButton = QtWidgets.QPushButton(self.directionGroupBox)
        self.leftButton.setGeometry(QtCore.QRect(20, 140, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.leftButton.setFont(font)
        self.leftButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.leftButton.setObjectName("leftButton")
        self.rightButton = QtWidgets.QPushButton(self.directionGroupBox)
        self.rightButton.setGeometry(QtCore.QRect(200, 140, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.rightButton.setFont(font)
        self.rightButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.rightButton.setObjectName("rightButton")
        self.gearGroupBox = QtWidgets.QGroupBox(self.manualTab)
        self.gearGroupBox.setGeometry(QtCore.QRect(590, 100, 150, 240))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.gearGroupBox.setFont(font)
        self.gearGroupBox.setObjectName("gearGroupBox")
        self.gearLcdNumber = QtWidgets.QLCDNumber(self.gearGroupBox)
        self.gearLcdNumber.setGeometry(QtCore.QRect(30, 50, 90, 120))
        self.gearLcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gearLcdNumber.setDigitCount(1)
        self.gearLcdNumber.setObjectName("gearLcdNumber")
        self.gearSlider = QtWidgets.QSlider(self.gearGroupBox)
        self.gearSlider.setGeometry(QtCore.QRect(20, 190, 110, 20))
        self.gearSlider.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gearSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gearSlider.setObjectName("gearSlider")
        self.brakeGroupBox = QtWidgets.QGroupBox(self.manualTab)
        self.brakeGroupBox.setGeometry(QtCore.QRect(60, 100, 170, 240))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.brakeGroupBox.setFont(font)
        self.brakeGroupBox.setObjectName("brakeGroupBox")
        self.brakeButton = QtWidgets.QPushButton(self.brakeGroupBox)
        self.brakeButton.setGeometry(QtCore.QRect(20, 50, 130, 170))
        font = QtGui.QFont()
        font.setPointSize(96)
        self.brakeButton.setFont(font)
        self.brakeButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.brakeButton.setObjectName("brakeButton")
        self.mainTabWidget.addTab(self.manualTab, "")

        self.retranslateUi(MainWidget)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        _translate = QtCore.QCoreApplication.translate
        self.simulationButton.setText(_translate("MainWidget", "Simulation"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.configTab), _translate("MainWidget", "Configuration"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.mappingTab), _translate("MainWidget", "Mapping"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.debugTab), _translate("MainWidget", "Debug"))
        self.directionGroupBox.setTitle(_translate("MainWidget", "Direction"))
        self.upButton.setText(_translate("MainWidget", "⇧"))
        self.downButton.setText(_translate("MainWidget", "⇩"))
        self.leftButton.setText(_translate("MainWidget", "⇦"))
        self.rightButton.setText(_translate("MainWidget", "⇨"))
        self.gearGroupBox.setTitle(_translate("MainWidget", "Gear"))
        self.brakeGroupBox.setTitle(_translate("MainWidget", "Brake"))
        self.brakeButton.setText(_translate("MainWidget", "℗"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.manualTab), _translate("MainWidget", "Manual Control"))

